// Master ACRM Question Bank (Part 2: Items 101 to 175+)
// Source Materials: Airframe Test Guide 2019 Highlighted, A&P Technician Airframe (Jeppesen)

window.ALL_AELE_QUESTIONS = window.ALL_AELE_QUESTIONS || [];

window.ALL_AELE_QUESTIONS.push(
  // SECTION 4: COMPOSITES, HYDRAULICS, LANDING GEAR & SYSTEMS (ITEMS 101-175+)
  {"id":"ACRM-101","subject":"Aircraft Construction, Repair and Modification","topic":"Composite Core Repair","question":"When repairing a punctured honeycomb sandwich core panel, the potting compound or core plug should be:","options":["A. Taper-sanded and cured under vacuum pressure with compatible structural adhesive","B. Filled with expanding foam only","C. Left open for drainage","D. Covered with duct tape"],"correct_answer":"A","explanation":"Honeycomb core repairs involve excavating damaged cells, inserting syntactic foam or pre-formed honeycomb core plug, and applying stepped scarf plies under vacuum pressure."},
  {"id":"ACRM-102","subject":"Aircraft Construction, Repair and Modification","topic":"Composite Scarf Repairs","question":"In structural solid laminate composite repairs, what is the standard recommended scarf taper ratio for sanding back damaged plies?","options":["A. 50:1 to 100:1 (taper length to laminate thickness)","B. 5:1","C. 2:1","D. 10:1"],"correct_answer":"A","explanation":"Structural composite scarfing requires gentle taper slopes of 50:1 to 100:1 to provide adequate bonding shear area across each individual ply layer."},
  {"id":"ACRM-103","subject":"Aircraft Construction, Repair and Modification","topic":"Composite Ply Orientation","question":"In composite laminate stacking sequences, a symmetrical quasi-isotropic layup is designated as:","options":["A. [0° / +45° / -45° / 90°]_s","B. [0° / 0° / 0° / 0°]","C. [90° / 90° / 90°]","D. [+45° / +45°]"],"correct_answer":"A","explanation":"A [0/+45/-45/90]_s layup provides uniform in-plane mechanical properties in all directions and prevents thermal curing warpage."},
  {"id":"ACRM-104","subject":"Aircraft Construction, Repair and Modification","topic":"Prepreg Storage","question":"Structural composite prepreg fabrics (pre-impregnated with uncured B-stage epoxy resin) must be stored:","options":["A. In freezers at 0°F (-18°C) or below to halt resin curing reaction","B. At room temperature in direct sunlight","C. In an autoclave","D. In water baths"],"correct_answer":"A","explanation":"Freezer storage retards cross-linking polymerization of the B-stage thermosetting epoxy matrix until layup and heat curing."},
  {"id":"ACRM-105","subject":"Aircraft Construction, Repair and Modification","topic":"Vacuum Bagging Components","question":"In a composite vacuum bagging layup, the porous film placed directly over the wet laminate to allow excess resin to pass into the bleeder is the:","options":["A. Release film (peel ply / porous separator)","B. Vacuum bag film","C. Sealant tape","D. Breather cloth"],"correct_answer":"A","explanation":"Porous peel ply allows air and excess resin to escape into the bleeder pad while providing a bondable textured surface upon removal."},
  {"id":"ACRM-106","subject":"Aircraft Construction, Repair and Modification","topic":"Hydraulic Fluids","question":"Which aircraft hydraulic fluid is synthetic phosphate ester-based, fire-resistant, and colored light purple?","options":["A. Skydrol (BMS 3-11 / SAE AS1241)","B. MIL-H-5606 (Mineral base, red)","C. MIL-H-83282 (Synthetic hydrocarbon, red)","D. Vegetable base (Blue)"],"correct_answer":"A","explanation":"Skydrol fluids are purple synthetic phosphate esters that are highly fire-resistant and require butyl rubber or Teflon seals."},
  {"id":"ACRM-107","subject":"Aircraft Construction, Repair and Modification","topic":"Hydraulic Seals","question":"O-ring packings used in Skydrol synthetic phosphate ester hydraulic systems must be manufactured from:","options":["A. Butyl rubber or Ethylene-Propylene (EPR/EPDM)","B. Nitrile (Buna-N) rubber","C. Neoprene","D. Natural rubber"],"correct_answer":"A","explanation":"Mineral-based fluids use Nitrile (Buna-N); Skydrol chemically attacks Nitrile and strictly requires Butyl or EPDM seals."},
  {"id":"ACRM-108","subject":"Aircraft Construction, Repair and Modification","topic":"Pascal's Law","question":"Pascal's Law states that pressure applied to an enclosed, incompressible liquid is transmitted:","options":["A. Undiminished in all directions and acts with equal force on equal areas perpendicular to container walls","B. Only in the direction of applied force","C. Inversely proportional to volume","D. Exclusively toward the lowest point"],"correct_answer":"A","explanation":"Pascal's Principle is the fundamental operating law for all aircraft hydraulic and pneumatic power transmission systems."},
  {"id":"ACRM-109","subject":"Aircraft Construction, Repair and Modification","topic":"Hydraulic Accumulators","question":"What is the primary function of a pneumatic-hydraulic accumulator in an aircraft hydraulic system?","options":["A. Store hydraulic fluid under gas pressure to supplement pump flow during peak demands, dampen pressure surges, and provide emergency actuation","B. Filter contamination","C. Cool the hydraulic fluid","D. Measure system flow rate"],"correct_answer":"A","explanation":"Accumulators hold a pressurized fluid reserve, absorb hydraulic line shocks, and provide auxiliary pressure during pump failure."},
  {"id":"ACRM-110","subject":"Aircraft Construction, Repair and Modification","topic":"Accumulator Pre-charge","question":"When checking or servicing the nitrogen gas pre-charge pressure in a hydraulic accumulator:","options":["A. Hydraulic system pressure must be zero (completely depressurized with system valves open)","B. System must be at maximum 3,000 psi operating pressure","C. Pumps must be operating","D. Reservoir must be pressurized"],"correct_answer":"A","explanation":"Accurate gas pre-charge measurement requires zero hydraulic fluid pressure acting against the internal piston or bladder."},
  {"id":"ACRM-111","subject":"Aircraft Construction, Repair and Modification","topic":"Hydraulic Actuator Force","question":"A hydraulic actuator has a piston area of 3.0 sq in. If hydraulic system pressure is 3,000 psi, what is the theoretical output force?","options":["A. 9,000 lbs","B. 1,000 lbs","C. 6,000 lbs","D. 12,000 lbs"],"correct_answer":"A","explanation":"Force = Pressure × Area = 3,000 psi × 3.0 sq in = 9,000 lbs."},
  {"id":"ACRM-112","subject":"Aircraft Construction, Repair and Modification","topic":"Hydraulic Relief Valves","question":"A thermal relief valve in an aircraft hydraulic subsystem is calibrated to open at:","options":["A. A pressure slightly higher than the main system relief valve to relieve pressure caused by thermal fluid expansion in trapped lines","B. 100 psi below operating pressure","C. Zero psi","D. Ambient atmospheric pressure"],"correct_answer":"A","explanation":"Thermal relief valves protect closed hydraulic circuits from over-pressurization when ambient heat expands trapped fluid."},
  {"id":"ACRM-113","subject":"Aircraft Construction, Repair and Modification","topic":"Landing Gear Oleo Struts","question":"In a conventional air-oil (oleo-pneumatic) landing gear shock strut, the landing impact shock is absorbed by \\_\\_\\_\\_ and taxi shocks are cushioned by \\_\\_\\_\\_.","options":["A. Forcing hydraulic oil through an internal metering orifice; compressed dry nitrogen gas","B. Nitrogen compression; oil vaporization","C. Mechanical steel coil springs; rubber snubbers","D. Solid rubber disks; oil friction"],"correct_answer":"A","explanation":"Fluid metered through an orifice dissipates high-energy touchdown impact kinetic energy; compressed nitrogen provides elastic taxi cushioning."},
  {"id":"ACRM-114","subject":"Aircraft Construction, Repair and Modification","topic":"Oleo Strut Servicing","question":"An oleo landing gear strut that bottoms out completely during normal landing impact is most likely:","options":["A. Low on hydraulic fluid","B. Overcharged with nitrogen","C. Seized by torque links","D. Overfilled with oil"],"correct_answer":"A","explanation":"Insufficient hydraulic fluid allows the piston to stroke through air without developing necessary hydraulic damping resistance."},
  {"id":"ACRM-115","subject":"Aircraft Construction, Repair and Modification","topic":"Aircraft Brake Systems","question":"Multiple-disc aircraft brakes on large commercial aircraft utilize stators and rotors constructed of carbon-carbon composite because:","options":["A. Carbon maintains high friction at extreme temperatures (above 2,000°F), resists brake fade, and weighs 40% less than steel","B. Carbon never wears out","C. Carbon is cheaper than cast iron","D. Carbon is flexible"],"correct_answer":"A","explanation":"Carbon brakes absorb massive kinetic heat energy without fading and offer substantial weight savings over steel discs."},
  {"id":"ACRM-116","subject":"Aircraft Construction, Repair and Modification","topic":"Anti-Skid Brake Systems","question":"In an aircraft electro-hydraulic anti-skid brake system, what sensor input triggers the anti-skid control valve to release brake pressure?","options":["A. A sudden rapid deceleration of wheel rotational speed indicating an impending wheel skid","B. Brake pedal pressure exceeding 500 psi","C. Throttle lever position","D. Pitot airspeed falling below 50 knots"],"correct_answer":"A","explanation":"Wheel speed transducers sense rapid wheel deceleration (skid onset), signaling the control unit to momentarily relieve brake hydraulic pressure."},
  {"id":"ACRM-117","subject":"Aircraft Construction, Repair and Modification","topic":"Landing Gear Shimmy Dampers","question":"A hydraulic shimmy damper attached to a nose landing gear assembly functions to:","options":["A. Prevent rapid, violent, uncommanded side-to-side castering oscillations of the nose wheel during high-speed ground rollout","B. Steer the nose wheel during flight","C. Lock the gear up in flight","D. Dampen vertical taxi shocks"],"correct_answer":"A","explanation":"Shimmy dampers resist high-frequency rotational oscillations through viscous fluid metering while permitting slow steering movements."},
  {"id":"ACRM-118","subject":"Aircraft Construction, Repair and Modification","topic":"Aircraft Cabin Pressurization","question":"Aircraft cabin pressurization is controlled by regulating the:","options":["A. Rate at which conditioned air is allowed to exit the cabin via the outflow valve","B. Compressor engine RPM","C. Size of the passenger windows","D. Altitude of the aircraft only"],"correct_answer":"A","explanation":"Turbine bleed air enters the cabin at a constant rate; the cabin pressure controller adjusts the variable outflow valve to maintain cabin altitude."},
  {"id":"ACRM-119","subject":"Aircraft Construction, Repair and Modification","topic":"Oxygen Systems","question":"A diluter-demand aircraft supplemental oxygen regulator delivers:","options":["A. A mixture of ambient cabin air and 100% oxygen that automatically increases oxygen percentage as cabin altitude rises, delivering pure oxygen above 32,000 ft","B. Continuous steady flow at all altitudes","C. Pure nitrogen","D. Low-pressure compressed air"],"correct_answer":"A","explanation":"Diluter-demand regulators supply oxygen only when the user inhales, automatically blending cabin air and pure oxygen based on cabin altitude."},
  {"id":"ACRM-120","subject":"Aircraft Construction, Repair and Modification","topic":"Chemical Oxygen Generators","question":"Chemical oxygen 'candles' (sodium chlorate generators) installed for passenger emergency drop-down masks generate oxygen by:","options":["A. A self-sustaining exothermic thermal decomposition reaction of sodium chlorate (NaClO3) and iron powder","B. Pressurized liquid oxygen evaporation","C. Electrolysis of water","D. Cryogenic boiling"],"correct_answer":"A","explanation":"An ignited chemical core produces continuous breathable oxygen for 12–22 minutes at high temperature (~500°F)."},
  {"id":"ACRM-121","subject":"Aircraft Construction, Repair and Modification","topic":"Pneumatic De-Icing Boots","question":"Inflatable rubber de-icing boots installed on aircraft wing leading edges function by:","options":["A. Periodically inflating with engine bleed air or vacuum pump pressure to physically break formed ice accumulations, which are blown away by relative wind","B. Heating the leading edge above boiling point","C. Spraying glycol continuously","D. Vibrating with ultrasound"],"correct_answer":"A","explanation":"De-ice boots are a de-icing (removal) system inflated cyclically after ice forms to crack and shed the ice layer."},
  {"id":"ACRM-122","subject":"Aircraft Construction, Repair and Modification","topic":"Thermal Anti-Ice Systems","question":"Thermal anti-icing systems on transport category aircraft prevent ice formation on wing leading edges and engine cowlings by:","options":["A. Continuously circulating hot engine bleed air (above 350°F) through internal leading-edge piccolo tubes","B. Spraying de-icing fluids","C. Applying electrical current directly through aluminum skin","D. Painting with hydrophobic wax"],"correct_answer":"A","explanation":"Thermal anti-ice is an anti-icing (prevention) system that heats leading edges continuously to evaporate water droplets on contact."},
  {"id":"ACRM-123","subject":"Aircraft Construction, Repair and Modification","topic":"Windshield Rain Removal","question":"Which method is widely used on commercial transport aircraft for rain removal from windshields during approach and landing?","options":["A. High-velocity engine bleed air pneumatic blast and electrical heating / mechanical wipers","B. Hand squeegees","C. Oil coating","D. Propeller wash only"],"correct_answer":"A","explanation":"Pneumatic rain-blast nozzles, mechanical wipers, and hydrophobic chemical repellents clear rain from flight deck windshields."},
  {"id":"ACRM-124","subject":"Aircraft Construction, Repair and Modification","topic":"Fire Detection Loops","question":"Continuous-loop fire and overheat detector systems (e.g. Kidde / Fenwal systems) operate based on:","options":["A. Thermistor resistance decrease or eutectic core melting upon exposure to heat along any point of the loop","B. Optical infrared cameras only","C. Bimetallic snap switches only","D. Melting solder wire"],"correct_answer":"A","explanation":"Continuous sensing tubes monitor electrical resistance or gas capacitance along their entire length to detect localized flames or overheat conditions."},
  {"id":"ACRM-125","subject":"Aircraft Construction, Repair and Modification","topic":"Aircraft Electrical Bonding","question":"Flexible braided copper bonding jumpers are installed across aircraft hinged control surfaces and structural joints to:","options":["A. Provide a low-resistance electrical return path for lightning strikes and static discharge, and prevent radio interference","B. Keep the control surface from falling off","C. Provide structural damping","D. Lubricate the hinge pins"],"correct_answer":"A","explanation":"Electrical bonding ensures uniform electrostatic potential across all airframe components to dissipate static electricity and lightning energy."},
  {"id":"ACRM-126","subject":"Aircraft Construction, Repair and Modification","topic":"Circuit Protection","question":"Aircraft electrical circuit breakers are designed primarily to protect the:","options":["A. Aircraft electrical wiring from overheating and fire caused by excessive current draw","B. Switch contacts","C. Generator brushes","D. Pilot from electric shock"],"correct_answer":"A","explanation":"Circuit breakers are sized to trip before electrical conductors reach temperatures that melt insulation or ignite fires."},
  {"id":"ACRM-127","subject":"Aircraft Construction, Repair and Modification","topic":"AC Generators (Alternators)","question":"The frequency of the alternating current produced by a brushless aircraft synchronous generator is governed by:","options":["A. Generator rotor rotational RPM and number of magnetic poles (f = P * RPM / 120)","B. System voltage regulator setting","C. Total electrical load connected","D. Battery state of charge"],"correct_answer":"A","explanation":"400 Hz constant-frequency AC power requires the generator to run at constant speed via an Integrated Drive Generator (IDG) or Constant Speed Drive (CSD)."},
  {"id":"ACRM-128","subject":"Aircraft Construction, Repair and Modification","topic":"Inverters","question":"A static or rotary inverter in an aircraft electrical system functions to:","options":["A. Convert Direct Current (DC) into Alternating Current (AC)","B. Convert AC to DC","C. Step down DC voltage","D. Regulate generator speed"],"correct_answer":"A","explanation":"Inverters convert DC battery power into 115V 400Hz AC power for critical flight instruments. (Transformer-Rectifiers convert AC to DC)."},
  {"id":"ACRM-129","subject":"Aircraft Construction, Repair and Modification","topic":"Pitot-Static Leak Testing","question":"When performing a static system leak check on an unpressurized aircraft, what is the maximum allowable leakage rate under FAR Part 43 Appendix E?","options":["A. Not more than 100 feet of altitude change in 1 minute when evacuated to 1,000 ft","B. Zero leakage allowed","C. 500 feet per minute","D. 250 feet per minute"],"correct_answer":"A","explanation":"FAR 43 Appendix E allows a maximum leakage of 100 ft per minute when tested at 1,000 ft above field pressure."},
  {"id":"ACRM-130","subject":"Aircraft Construction, Repair and Modification","topic":"Altimeter Setting","question":"When the local barometric altimeter setting is dialed into the Kollsman window, the altimeter pointers read:","options":["A. True altitude above mean sea level (MSL) at field elevation","B. Absolute height above ground (AGL)","C. Pressure altitude","D. Density altitude"],"correct_answer":"A","explanation":"The Kollsman window adjusts the barometric aneroid capsule baseline so the instrument displays indicated altitude referenced to MSL."},
  {"id":"ACRM-131","subject":"Aircraft Construction, Repair and Modification","topic":"Magnetic Compass Deviation","question":"Magnetic compass deviation error is caused by:","options":["A. Local magnetic fields generated by aircraft electrical circuits, avionics, and ferrous airframe structures","B. The earth's magnetic poles","C. Gyroscopic precession","D. Centrifugal force in turns"],"correct_answer":"A","explanation":"Deviation is the compass error induced by magnetic equipment within the aircraft itself, corrected by adjusting compensation magnets during compass swinging."},
  {"id":"ACRM-132","subject":"Aircraft Construction, Repair and Modification","topic":"Aircraft Woodwork Grain Slope","question":"The maximum allowable slope of the grain in structural aircraft wood spars is:","options":["A. 1 in 15 (1:15 slope)","B. 1 in 8","C. 1 in 20","D. 1 in 5"],"correct_answer":"A","explanation":"FAA AC 43.13-1B restricts grain deviation to not steeper than 1 inch in 15 inches along the length of the member."},
  {"id":"ACRM-133","subject":"Aircraft Construction, Repair and Modification","topic":"Wood Rot & Fungi","question":"Any presence of decay, dote, or dry rot in an aircraft structural wooden spar requires:","options":["A. Immediate rejection and replacement of the affected spar","B. Scraping and varnishing","C. Reinforcing with plywood gussets","D. Epoxy injection"],"correct_answer":"A","explanation":"Wood decay and rot destroy the cellulose fibers, causing total loss of shear and bending strength; no rot is acceptable."},
  {"id":"ACRM-134","subject":"Aircraft Construction, Repair and Modification","topic":"Dope Application","question":"Aircraft cellulose nitrate and butyrate dopes applied to natural cotton fabric coverings function to:","options":["A. Tautens (shrink) the fabric, fill the weave, and provide an airtight, weather-resistant structural skin","B. Prevent combustion","C. Increase fabric weight","D. Lubricate the fabric"],"correct_answer":"A","explanation":"Dopes shrink the fabric drum-tight and encapsulate the fibers to make them airtight and weatherproof."},
  {"id":"ACRM-135","subject":"Aircraft Construction, Repair and Modification","topic":"Fabric Re-covering Testing","question":"Aircraft fabric must be replaced (un-airworthy) when its tensile strength deteriorates below:","options":["A. 70% of its original new designated minimum strength","B. 50%","C. 90%","D. 85%"],"correct_answer":"A","explanation":"Under FAA standards, aircraft fabric is unairworthy when its strength drops below 70% of the minimum certified strength for that aircraft class."},
  {"id":"ACRM-136","subject":"Aircraft Construction, Repair and Modification","topic":"Rivet Hole Drilling","question":"When drilling holes for solid shank rivets, what drill size is used for 1/8-inch (3/32\" / #30) rivets?","options":["A. #30 drill bit (0.1285 inch)","B. 1/8 inch drill bit exactly (0.1250 inch)","C. #40 drill bit","D. #21 drill bit"],"correct_answer":"A","explanation":"Rivet holes are drilled slightly oversized for clearance: 3/32\" uses #40 (0.098\"), 1/8\" uses #30 (0.1285\"), 5/32\" uses #21 (0.159\"), 3/16\" uses #11 (0.191\")."},
  {"id":"ACRM-137","subject":"Aircraft Construction, Repair and Modification","topic":"Flush Patch Riveting","question":"A flush skin patch repair on an aircraft fuselage or wing consists of:","options":["A. A filler plate matching the original skin cutout thickness, backed by a riveted internal doubler plate","B. An external lap patch only","C. A welded patch","D. Fiber glass tape"],"correct_answer":"A","explanation":"Flush repairs maintain external aerodynamic contour by setting a filler plug flush with the skin over an underlying reinforcement doubler."},
  {"id":"ACRM-138","subject":"Aircraft Construction, Repair and Modification","topic":"Major Alteration Records","question":"Following the completion of a major structural repair or major alteration, what documentation must be completed and submitted to the aviation authority?","options":["A. FAA Form 337 (Major Repair and Alteration Form) and aircraft logbook signoff","B. Bill of Sale","C. Pilot logbook","D. Airworthiness directive"],"correct_answer":"A","explanation":"Major repairs and alterations require an approved FAA Form 337 and an entry in the permanent aircraft maintenance records."},
  {"id":"ACRM-139","subject":"Aircraft Construction, Repair and Modification","topic":"Cable Rigging Tension","question":"When checking flight control cable tension with a tensiometer, the technician must consult the rigging chart to correct for:","options":["A. Ambient temperature at the time of measurement","B. Humidity","C. Aircraft fuel load","D. Tire pressure"],"correct_answer":"A","explanation":"Cable rigging tension charts specify tension curves plotted directly as a function of ambient temperature."},
  {"id":"ACRM-140","subject":"Aircraft Construction, Repair and Modification","topic":"Flight Control Balancing","question":"Following repainting or structural repair of an aileron, elevator, or rudder, the surface must be:","options":["A. Statically re-balanced within manufacturer mass balance tolerances to prevent high-speed flutter","B. Weighted at the trailing edge","C. Greased","D. Flown immediately"],"correct_answer":"A","explanation":"Adding weight aft of the hinge line can cause violent aerodynamic flutter; re-balancing within strict mass limits is mandatory."}
);
